# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_products_tiny_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategori',
            new_name='ProductCategory',
        ),
    ]
