# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180610_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='href',
            field=models.CharField(default='#', max_length=64, verbose_name='Item link'),
            preserve_default=False,
        ),
    ]
